### ISSUE TITLE
[TGL] [SDW]: max98373 SDW error at soc_component_read_no_lock

### ISSUE THREAD

**Issue by naveen-manohar** [thesofproject/linux#2473]
Observe following Log randomly, during stress cycling.. Speaker Audio-Functionality post this scenario is yet to be verified as its a cold-reboot stress test.
Log: [system_logs.txt](https://github.com/thesofproject/linux/files/5285932/system_logs.txt)
```
[ 1432.644301] max98373 sdw:1:19f:8373:0:7: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:7: -16
[ 1432.644318] max98373 sdw:1:19f:8373:0:7: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:7: -16
[ 1432.644331] max98373 sdw:1:19f:8373:0:7: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:7: -16
[ 1432.644563] max98373 sdw:1:19f:8373:0:3: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:3: -16
[ 1432.644576] max98373 sdw:1:19f:8373:0:3: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:3: -16
[ 1432.644586] max98373 sdw:1:19f:8373:0:3: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:3: -16
[ 1432.748544] max98373 sdw:1:19f:8373:0:7: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:7: -16

```
Recipe Based on SoF_V0.7 Release
Hardware: Volteer Proto Board

**Comment by naveen-manohar** [comment]
Customer reported an issue which broke down into no audio with the same error signature.. Can we bump the priority in-par with customer's priority

**Comment by plbossart** [comment]
@naveen-manohar unless you help us by using the topic/sof-dev kernel and providing more detailed logs, changing the priority is not going to help. Keep in mind I am the only SoundWire support for the next week or so (Chinese Fall festival)....

Specifically I don't see where "soc_component_read_no_lock" is called and what sequence leads to this problem. Please add dynamic debug for the soundwire parts as well, e.g. by adding this in /etc/modprobe.d/sof-ddbug.conf
[Uploading ddebug.txt…]()

**Comment by naveen-manohar** [comment]
Sure @plbossart , ww40.5 is India Site Holiday, by ww41.1 EoD, shall post the specified data.

**Comment by naveen-manohar** [comment]
With chrome latest kernel based on SoF_v010 and was to able to reproduce issue during warm_boot stress test with debug logs..
Seems like the DSP fails to enter D3 during certain iteration and further access to soundwire device fails
Logs: 
[dmesg-issue_ipc_timeout.log](https://github.com/thesofproject/linux/files/5323046/dmesg-issue_ipc_timeout.log) - FAILS
[dmesg-working.log](https://github.com/thesofproject/linux/files/5323047/dmesg-working.log) - PASS

```
sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x20140000 successful
sof-audio-pci 0000:00:1f.3: ipc tx: 0x40010000
sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x40010000 size 76
sof-audio-pci 0000:00:1f.3: info: preventing DSP entering D3 state to preserve context
sof-audio-pci 0000:00:1f.3: unknown ROM status value ffffffff
sof-audio-pci 0000:00:1f.3: invalid header size 0xffffffff. FW oops is bogus
sof-audio-pci 0000:00:1f.3: error: unexpected fault 0xffffffff trace 0xffffffff
sof-audio-pci 0000:00:1f.3: error: hda irq intsts 0x00000000 intlctl 0xc0000000 rirb 00
sof-audio-pci 0000:00:1f.3: error: dsp irq ppsts 0x00000000 adspis 0x00000000
sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
sof-audio-pci 0000:00:1f.3: ctx_save ipc error -110, proceeding with suspend
sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x9010f0f successful
sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x9000f0f successful
sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000000 at  00000044
sof-audio-pci 0000:00:1f.3: Debug PCIW: 00000010 at  00000044
sof-audio-pci 0000:00:1f.3: Turning i915 HDAC power 0
sof-audio-pci 0000:00:1f.3: Current DSP power state: D3
max98373 sdw:1:19f:8373:0:7: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:7: -16
```

Please let me know if any more information required.

**Comment by kv2019i** [comment]
Discussed with @naveen-manohar and we'll try to get:
- DSP FW logs
- more debug from the codec driver

One thing that pops up in the error case log is that we are getting traces from the codec driver after 
2020-10-04T15:35:01,501726+05:30 intel-sdw intel-sdw.1: intel_link_power_down: powering down all links
...
2020-10-04T15:35:27,168791+05:30 max98373 sdw:1:19f:8373:0:7: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:7: -16

The ordering is not right, something is wrong here.

**Comment by kv2019i** [comment]
Quick update. The  soc_component_read_no_lock errors are probably amixer reads after all, and regmap_read returns -EBUSY if regmap is in cache_only mode, which would be the case when powered down, so these look harmless in the end. So the main question is now to why the IPC fails.

**Comment by naveen-manohar** [comment]
Thanks @kv2019i for the quick support.. Sure I'm working on the DSP FW logs during Failure Scenario
Things is, Issue is reproduced in stress test, so I need to make find some way to stop the test during failure.
Let me reproduce and update with FW trace. Thanks

**Comment by naveen-manohar** [comment]
attached firmware trace..
[trace.log](https://github.com/thesofproject/linux/files/5326693/trace.log)
[dmesg.log](https://github.com/thesofproject/linux/files/5326694/dmesg.log)

**Comment by plbossart** [comment]
> Quick update. The soc_component_read_no_lock errors are probably amixer reads after all, and regmap_read returns -EBUSY if regmap is in cache_only mode, which would be the case when powered down, so these look harmless in the end. So the main question is now to why the IPC fails.

can you share a pointer to this behavior @kv2019i? that's not intended, the point about cache_only mode was to avoid sending commands on the bus but there's no reason to return an error.

**Comment by plbossart** [comment]
@naveen-manohar I don't see a smoking gun but I don't understand the sequence either. it looks like in the tests the failure happens on the first suspend, which is not really a stress test...I also don't see if this is due to pm_runtime or a system suspend. more info would be good here.

**Comment by naveen-manohar** [comment]
Hi @plbossart ,
Apologies for not sharing the exact test being tried..
The stress test is about cold-boot test ran using a set of scripts.. sequence is like below:
**Boot -> Check all devices are loaded -> Dump corresponding logs -> cold-reboot -> redo test till iteration specified.**
Here Cold reboot = ectool reboot_ec cold at-shutdown, shutdown -h now

Each iteration's boot log/dump will be stored in a separate folder..
Finally i did a grep to check any iteration failed..

**Comment by ranj063** [comment]
@plbossart looking at intel_suspend_runtime() it looks we disable interrupts before powering down the links. Is that intended?

**Comment by kv2019i** [comment]
@plbossart wrote:
> @kv2019i wrote:
>> -EBUSY if regmap is in cache_only mode, which would be the case when powered down, so these look harmless in the end. 

> can you share a pointer to this behavior @kv2019i? that's not intended, the point about cache_only mode was to avoid sending commands on the bus but there's no reason to return an error.

Basicly I was searching the codebase where codec soc_component_read I/O would return -EBUSY and pretty much the only place
is regmap.c:_regmap_read(). There's code that checks map->cache_only and returns -EBUSY in this case.

**Comment by plbossart** [comment]
> @plbossart looking at intel_suspend_runtime() it looks we disable interrupts before powering down the links. Is that intended?

yes, we let the workqueue complete, then disable Cadence IP interrupts then power down links.

@naveen-manohar can you double-check if you have the patch "soundwire: cadence: fix race condition between suspend and Slave device alerts", that's the only thing I can think of on the suspend path that we fixed recently (August).

**Comment by naveen-manohar** [comment]
@plbossart : I don't observe this patch in my Code-base. Thank you this seems related.
I'm trying to the issue with this patch now..

If here too, if i observe issue, then as @ranj063 recommended shall move to SDW upstream backported recipe and update..

**Comment by naveen-manohar** [comment]
I quickly ran the test and observe with following patch too issue is observed - "soundwire: cadence: fix race condition between suspend and Slave device alerts"
Switching to SDW upstream backported recipe blindly.. If any suggestions please share..

**Comment by plbossart** [comment]
@kv2019i the-EBUSY should not happen:

````c
static int _regmap_read(struct regmap *map, unsigned int reg,
			unsigned int *val)
{
	int ret;
	void *context = _regmap_map_get_context(map);

	if (!map->cache_bypass) {
		ret = regcache_read(map, reg, val);
		if (ret == 0)
			return 0; <<< we should return here?
	}

	if (map->cache_only)
		return -EBUSY;
````

I think we have a case where the cache_bypass and cache_only are not correctly set?

**Comment by naveen-manohar** [comment]
Just an Update on the experiment I was trying,
With SDW upstream kernel too, I was able to **reproduce the IPC issue**.. within 5 iterations

Checked @plbossart's suggestion to remove the regcache_mark_dirty entry during suspend.. **But still Issue Persists..** 
I do observe eBusy- `max98373 sdw:1:19f:8373:0:3: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:3: -16`

Hence I re-tried with removing regcache_mark_dirty in _io_init(), **still issue persists..**
```
@@ -450,7 +450,7 @@ static int max98373_io_init(struct sdw_slave *slave)

        if (max98373->pm_init_once) {
                regcache_cache_bypass(max98373->regmap, false);
-               regcache_mark_dirty(max98373->regmap);
+//             regcache_mark_dirty(max98373->regmap);

```

**Comment by plbossart** [comment]
@naveen-manohar can you try disabling pm_runtime then? 

options snd-sof-pci sof_pci_debug=1

Just to see if leaving everything on helps.

**Comment by naveen-manohar** [comment]
@plbossart : With disabling pm_rt it works fine.. tried 10 iterations.

**Comment by plbossart** [comment]
Thanks @naveen-manohar, that helps. I can't point to a root-cause yet but at least there's a sequence that works and a sequence that doesn't.

Can we try another test where we disable pm_runtime at the SoundWire master level. This should work:

options soundwire_intel sdw_md_flags=0x01010101

**Comment by plbossart** [comment]
@naveen-manohar can you also remind me what the test does, is this system suspend from S0 to S3, or S0 to S0ix? Also what the state of the PCI device, D0 or D0i3?

**Comment by naveen-manohar** [comment]
Sure @plbossart shall try the experiments and update..
Just an update is that, i was applying certain debug prints to check the codec EBUSY in https://github.com/thesofproject/linux/blob/topic/sof-dev/drivers/base/regmap/regmap.c#L2676
And found that no IPC issue was observed when i do the stress test.. Seems like a timing issue ?

The stress test is normal ec-cold boot for certain iterations.. (similar to unplug and replug of power)
Boot -> Check all devices are loaded -> Dump corresponding logs -> cold-reboot -> redo test till iteration specified

**Comment by plbossart** [comment]
@naveen-manohar this definitively looks like a race condition.

Can you share details of the test? 

In the past, we've had cases where we do we rapid system suspend/resume, there's an interference with pm_runtime. If you can try streching the cases so as to make sure that all pm_runtime is complete, e.g. suspend every 30s, that would help check what happens when you suspend from an already idle state.

And also can you confirm you are able to run the SOF test cases on this platform - outside of the Chrome ones? You should be able to run sof-test/test-case/runall.sh, if you already see a problem there it's not so good.

**Comment by ranj063** [comment]
> And also can you confirm you are able to run the SOF test cases on this platform - outside of the Chrome ones? You should be able to run sof-test/test-case/runall.sh, if you already see a problem there it's not so good.

@plbossart seems like kern.log is not standard on the chromebook. So I dont think Naveen will be able to run sof-test on his device

**Comment by plbossart** [comment]
> > And also can you confirm you are able to run the SOF test cases on this platform - outside of the Chrome ones? You should be able to run sof-test/test-case/runall.sh, if you already see a problem there it's not so good.
> 
> @plbossart seems like kern.log is not standard on the chromebook. So I dont think Naveen will be able to run sof-test on his device

Oh man, that's crazy. Can't we install Ubuntu and retry? I mean, if we can't reproduce tests it's *really hard* to debug anything.

**Comment by naveen-manohar** [comment]
Regarding Test being tried(sent the scipt in mail):
```
        # Boot to OS
        # Capture all device info.
	# Cold boot at S5
	ectool reboot_ec cold at-shutdown
	shutdown -h now
         # check iteration to repeat

```
@plbossart: I tried options soundwire_intel sdw_md_flags=0x01010101, issue Persists.
On Chromebook kern.log isn't available, I'm still checking this.

Thanks @plbossart @ranj063 for the support..

**Comment by kv2019i** [comment]
@plbossart wrote:
> Oh man, that's crazy. Can't we install Ubuntu and retry? I mean, if we can't reproduce tests it's _really hard_ to debug anything.

That's a known limitation of sof-test currently. We've talked about this with @marc-hb , but not on the roadmap currently.

**Comment by marc-hb** [comment]
sof-test supports Ubuntu 20.04 only. You could probably hack it and make some tests work on some other Linux desktop distribution(s) in a reasonable time (patches welcome) but for a Chromebook I wouldn't hold my breath because ChromeOS is very different.

BTW the plan is to drop the dependency on `kern.log` and focus on `journalctl` instead.

**Comment by naveen-manohar** [comment]
Tried experimenting by modifying the SOF device RT delay to 4000 & delay wrt sdw master .. Still IPC Fails

**Comment by plbossart** [comment]
@naveen-manohar I was suggesting the other direction, reduce the pm_runtime delay and increase the delay within the test script. The idea is to see if there's a conflict between pm_runtime suspend and system suspend/reboot.

**Comment by plbossart** [comment]
> sof-test supports Ubuntu 20.04 only. You could probably hack it and make some tests work on some other Linux desktop distribution(s) in a reasonable time (patches welcome) but for a Chromebook I wouldn't hold my breath because ChromeOS is very different.
> 
> BTW the plan is to drop the dependency on `kern.log` and focus on `journalctl` instead.

I suggest we really rethink the whole thing here. The effect is that we have no way of qualifying the backport in the same conditions as the initial upstream code. That's not good.

**Comment by ranj063** [comment]
> @naveen-manohar I was suggesting the other direction, reduce the pm_runtime delay and increase the delay within the test script. The idea is to see if there's a conflict between pm_runtime suspend and system suspend/reboot.

@plbossart I just confirmed with @naveen-manohar . The problem is seen with suspend stress tests too. So its not just the shutdown related race.

**Comment by marc-hb** [comment]
@plbossart we currently have a messy mix of `dmesg`, `kernel.log` and `journalctl`. The short term goal is to clean up that mess and unify to `journalctl`, once that's done then we can create some abstraction/indirection to support whatever ChromeOS uses. @naveen-manohar  it `rsyslogd` still?

Note this is only about scanning logs, I bet we have many other portability issues here and there.

**Comment by plbossart** [comment]
> > @naveen-manohar I was suggesting the other direction, reduce the pm_runtime delay and increase the delay within the test script. The idea is to see if there's a conflict between pm_runtime suspend and system suspend/reboot.
> 
> @plbossart I just confirmed with @naveen-manohar . The problem is seen with suspend stress tests too. So its not just the shutdown related race.

did you mean 'system suspend stress tests'? If yes, I would still like to rule out or confirm an interference between 'pm_runtime suspend' and 'system suspend'.

**Comment by naveen-manohar** [comment]
JFYI, Issue is observed on I2S SKU based EVT boards too, so i guess its more to do with SoF_driver & DSP FW timing than Soundwire Driver.
Issue reproduced during normal boot 2/10 times.
Log: [dmesg_i2s_fw_load_fail.log](https://github.com/thesofproject/linux/files/5353001/dmesg_i2s_fw_load_fail.log)
`2020-10-07T19:00:56,317901+05:30 sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x40010000 size 76
2020-10-07T19:00:56,318106+05:30 sof-audio-pci 0000:00:1f.3: invalid header size 0xffffffff. FW oops is bogus
2020-10-07T19:00:56,318110+05:30 sof-audio-pci 0000:00:1f.3: error: unexpected fault 0xffffffff trace 0xffffffff
2020-10-07T19:00:56,318144+05:30 sof-audio-pci 0000:00:1f.3: error: hda irq intsts 0x00000000 intlctl 0xc0000000 rirb 00
2020-10-07T19:00:56,318147+05:30 sof-audio-pci 0000:00:1f.3: error: dsp irq ppsts 0x00000000 adspis 0x00000000
2020-10-07T19:00:56,318175+05:30 sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003`
Wasn't keeping from past 2 days, shall resume my work activities from ww42.1 & update promptly

**Comment by sathya-nujella** [comment]
> JFYI, Issue is observed on I2S SKU based EVT boards too, so i guess its more to do with SoF_driver & DSP FW timing than Soundwire Driver.
> Issue reproduced during normal boot 2/10 times.
> Log: [dmesg_i2s_fw_load_fail.log](https://github.com/thesofproject/linux/files/5353001/dmesg_i2s_fw_load_fail.log)
> `2020-10-07T19:00:56,317901+05:30 sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x40010000 size 76 2020-10-07T19:00:56,318106+05:30 sof-audio-pci 0000:00:1f.3: invalid header size 0xffffffff. FW oops is bogus 2020-10-07T19:00:56,318110+05:30 sof-audio-pci 0000:00:1f.3: error: unexpected fault 0xffffffff trace 0xffffffff 2020-10-07T19:00:56,318144+05:30 sof-audio-pci 0000:00:1f.3: error: hda irq intsts 0x00000000 intlctl 0xc0000000 rirb 00 2020-10-07T19:00:56,318147+05:30 sof-audio-pci 0000:00:1f.3: error: dsp irq ppsts 0x00000000 adspis 0x00000000 2020-10-07T19:00:56,318175+05:30 sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003`
> 
> Am not keeping well from past 2 days, shall resume my work activities from ww42.1 & update promptly

Thank you @naveen-manohar .
DUT: System with speaker amp and headset codec in I2S  (Maxim98373- I2S  + RT5682-I2S)
With the latest Google-Kernel:5.4 + SOF fw & tplg with Max98373-DSM enabled + Max98373-UUID-smart amp component sent to SOF fw.
Able to reproduce the issue in this scenario:
1. Play sound on to speaker -> stop playback -> we see ipc timed out and context save error.
2. This problem does not happen with headset stream (atleast in my limited tests)
=====
[  342.545884] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 0 dir 0 cmd 0   //stream 0 is speaker
[  342.545893] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60050000
[  342.546107] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60050000
[  342.546113] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x140000 successful
[  342.546117] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60030000
[  342.546224] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60030000
[  342.546282] sof-audio-pci 0000:00:1f.3: pcm: free stream 0 dir 0
[  342.546324] sof-audio-pci 0000:00:1f.3: pcm: close stream 0 dir 0
[  345.040458] sof-audio-pci 0000:00:1f.3: ipc tx: 0x40010000
[  345.542258] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x40010000 size 76
[  345.542281] sof-audio-pci 0000:00:1f.3: unknown ROM status value ffffffff
[  345.542328] sof-audio-pci 0000:00:1f.3: invalid header size 0xffffffff. FW oops is bogus
[  345.542330] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0xffffffff trace 0xffffffff
[  345.542354] sof-audio-pci 0000:00:1f.3: error: hda irq intsts 0x00000000 intlctl 0xc0000000 rirb 00
[  345.542355] sof-audio-pci 0000:00:1f.3: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[  345.542377] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
[  345.542378] sof-audio-pci 0000:00:1f.3: ctx_save ipc error -110, proceeding with suspend
[  345.542479] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x9010f0f successful
[  345.542486] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[  345.542500] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[  345.542565] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000010 at  00000044
[  345.542586] sof-audio-pci 0000:00:1f.3: Turning i915 HDAC power 0
[  345.542609] sof-audio-pci 0000:00:1f.3: Current DSP power state: D3

Did chat with @ranj063 .  Want to see if this problem happens in previous versions and also with DSM disabled.

+ @RDharageswari  to see in to SOF side patches with Max98373 - DSM enabled .

Thank you!

**Comment by ranj063** [comment]
Seems like this issue is specific to the FW DSM patches. Bisect in progress @RDharageswari FYI

**Comment by RanderWang** [comment]
> Quick update. The soc_component_read_no_lock errors are probably amixer reads after all, and regmap_read returns -EBUSY if regmap is in cache_only mode, which would be the case when powered down, so these look harmless in the end. So the main question is now to why the IPC fails.

yes, the soc_component_read_no_lock err was exactly as Kai's idea. I got this error before but it is harmless.

**Comment by RanderWang** [comment]
tested 1000 cycles with v10. can't reproduce it.

**Comment by naveen-manohar** [comment]
> > Quick update. The soc_component_read_no_lock errors are probably amixer reads after all, and regmap_read returns -EBUSY if regmap is in cache_only mode, which would be the case when powered down, so these look harmless in the end. So the main question is now to why the IPC fails.
> 
> yes, the soc_component_read_no_lock err was exactly correct as Kai's idea. I got this error before but it is harmless.
> 
> more detail: some registers can't be access when codec is suspended. please check #2226 to recall everything.

ACK, I verified it by applying prints in regmap. More Explanation on SDW error log Attached:
```
[ 18.144826] max98373 sdw:1:19f:8373:0:7: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:7: -16
[ 18.144846] naveen _regmap_read+ Line=2521 reg=8276, cache_bypass=0, cache_only=1, regmap_readable=-1362004410
[ 18.144847] max98373 sdw:1:19f:8373:0:7: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:7: -16
[ 18.144864] naveen _regmap_read+ Line=2521 reg=8278, cache_bypass=0, cache_only=1, regmap_readable=-1362004410
[ 18.144869] naveen _regmap_read+ Line=2521 reg=8274, cache_bypass=0, cache_only=1, regmap_readable=-1362004410
[ 18.144870] naveen _regmap_read+ Line=2521 reg=8274, cache_bypass=0, cache_only=1, regmap_readable=-1362004410
[ 18.144873] naveen _regmap_read+ Line=2521 reg=8274, cache_bypass=0, cache_only=1, regmap_readable=-1362004410
[ 18.144878] naveen _regmap_read+ Line=2521 reg=8273, cache_bypass=0, cache_only=1, regmap_readable=-1362004410
[ 18.144881] naveen _regmap_read+ Line=2521 reg=8277, cache_bypass=0, cache_only=1, regmap_readable=-1362004410
[ 18.144882] max98373 sdw:1:19f:8373:0:7: ASoC: error at soc_component_read_no_lock on sdw:1:19f:8373:0:7: -16
```
Notice the error when occurred, regmap tried to read 8276(0x2054) or 8277(0x2055).
These two registers are volatile registers which shows amp ADC value. (Not important registers actually)
The error is happening when the regmap try to read volatile register in cache_only mode.
It just did right thing by returning -EBUSY. Actual h/w read is not supported for cache_only mode because the IC could be in suspend(power off) state.

**Comment by naveen-manohar** [comment]
JFYI,
As @RDharageswari suggested tried the DSP FW built removing DSM changes, with this DSP FW IPC timeout issue is not observed for 20 iterations that I tried.. Earlier I was able to reproduce the issue within 5 cycles.

**Comment by plbossart** [comment]
@naveen-manohar I think you have a corner case that we never thought about. 

what happens if those two registers are no longer exposed in regmap? Can we do a quick hack to remove them?

another possibility is that we modify regmap so that on each access to such a register we do a pm_runtime_get_sync() to wait for the bus to be operational. @bardliao what do you think?

**Comment by bardliao** [comment]
> @naveen-manohar I think you have a corner case that we never thought about.
> 
> what happens if those two registers are no longer exposed in regmap? Can we do a quick hack to remove them?
> 
> another possibility is that we modify regmap so that on each access to such a register we do a pm_runtime_get_sync() to wait for the bus to be operational. @bardliao what do you think?

I don't think we need to wake up codec to get the ADC value. The value is actually meaningless when the codec is in suspended. IMHO, it is better to avoid reading those register when codec is suspended than wake it up and get the value.

**Comment by naveen-manohar** [comment]
> > @naveen-manohar I think you have a corner case that we never thought about.
> > what happens if those two registers are no longer exposed in regmap? Can we do a quick hack to remove them?
> > another possibility is that we modify regmap so that on each access to such a register we do a pm_runtime_get_sync() to wait for the bus to be operational. @bardliao what do you think?
> 
> I don't think we need to wake up codec to get the ADC value. The value is actually meaningless when the codec is in suspended. IMHO, it is better to avoid reading those register when codec is suspended than wake it up and get the value.

Actually there were 3 such registers, have removed and verified Functionality. Further have added @ryans-lee to ACK - 
https://github.com/thesofproject/linux/pull/2507

**Comment by plbossart** [comment]
@naveen-manohar @RanderWang I don't understand what the root cause for this error might be.

This can only happen when

cache_bypass == true && cache_only == true, which seems to be an impossible case

Or 

cache_bypass = false and register is volatile && cache_only == true

````diff
diff --git a/drivers/base/regmap/regmap.c b/drivers/base/regmap/regmap.c
index 5db536ccfcd6..961362755697 100644
--- a/drivers/base/regmap/regmap.c
+++ b/drivers/base/regmap/regmap.c
@@ -2680,7 +2680,7 @@ static int _regmap_read(struct regmap *map, unsigned int reg,
                        return 0;
        }
 
-       if (map->cache_only)
+       if (map->cache_only && !regmap_volatile(map, reg))
                return -EBUSY;
 
        if (!regmap_readable(map, reg))
````

[volatile.diff.txt](https://github.com/thesofproject/linux/files/5404739/volatile.diff.txt)

In theory if we attempt to read from the device while in suspend, we already resume the entire bus and codec.

I really don't see why we should remove those volatile registers in all cases, I believe we will be missing on functionality by doing so.

Thanks!

**Comment by RanderWang** [comment]
> @naveen-manohar @RanderWang I don't understand what the root cause for this error might be.
> 
> 
> In theory if we attempt to read from the device while in suspend, we already resume the entire bus and codec.

One exception case: user queries alsa mixer settings by "amixer cget numid = xxxx"
