### ISSUE TITLE
HDMI monitor connection not visible via ALSA on TGL NUC

### ISSUE THREAD

**Issue by padmashree9110** [thesofproject/linux#2829]
Description
SOF-HDA cards not getting listed 

Platform
TIGER LAKE NUC

kernel log
[dmesg.log](https://github.com/thesofproject/linux/files/6278397/dmesg.log)

Firmware tag v1.6.1

steps to reproduce
1> Install ubuntu20.04 on TIGER LAKE NUC
2> install chrome kernel 5.4.76-cvhb
3> Rebuilt above kernel adding parameter "CONFIG_SND_SOC_SOF_TIGERLAKE_SUPPORT". .config file for this is attached 
      
[config.txt](https://github.com/thesofproject/linux/files/6278458/config.txt)

4>$git clone https://github.com/thesofproject/sof-bin.git
     $git checkout v1.6.1 -b local/v1.6.1
     $sudo ./go.sh
    This step worked fine.
5> Reboot host.
6> As still it was listing legacy HDA cards. Tried adding below changes
   * added "options snd-intel-dspcfg dsp_driver=1" in /etc/modprobe.d/alsa-base.conf
   * added "blacklist-dsp.conf" in /etc/modprobe.d/
   
[blacklist-dsp.txt](https://github.com/thesofproject/linux/files/6278409/blacklist-dsp.txt)

  7> Reboot host

After above steps, no sound cards detected.

inxi -A | grep driver
Audio:     Device-1: Intel driver: N/A

cat /proc/asound/cards
--- no soundcards ---

**Comment by plbossart** [comment]
@padmashree9110 if you want to force SOF to be used on a platform without DMIC or SoundWire, you have to use 
added "options snd-intel-dspcfg dsp_driver=3" in /etc/modprobe.d/alsa-base.conf

**Comment by padmashree9110** [comment]
@plbossart Thanks for the suggestion. i am able to list sof sound card now. HDMI audio is not working whereas 3.5mm is working fine. Any suggestions?

**Comment by padmashree9110** [comment]
@plbossart : i was able to list cad and also hear audio with 3.5mm initially. But I am facing issues after reboot. Sometimes it is not loading card only. and after " sudo alsa force-reload" it lists the card. But after this audio is not working and now in "settings->sound>output/input device" is not showing sof-snd cards.

But it lists the card

$cat /proc/asound/cards
  0 [sofhdadsp      ]: sof-hda-dsp - sof-hda-dsp
                      IntelCorporation-NUC11PAHi7-M15513_302-NUC11PABi7

$ sudo aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sofhdadsp [sof-hda-dsp], device 0: HDA Analog (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 1: HDA Digital (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 3: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 4: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 5: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

 Anything to be done to make it work again?

**Comment by plbossart** [comment]
@padmashree9110 I don't know what 'sudo alsa force-reload' is, never used it. I suggest you first try with a standard distribution, I don't know if the chrome kernel can support HDaudio platforms too well, Chromebooks do not use HDaudio w/ SOF

**Comment by kv2019i** [comment]
@padmashree9110 That sounds like mixer settings are not set correctly after the reload. Could you please try a recent Fedora or Ubuntu live image to confirm audio works on your system (including HDMI)? I recommend dumping "alsa-info" output on the live-image boot (once you've confirmed audio works), then boot with the Chrome kernel, run "alsa-info" again and compare the differences.

**Comment by padmashree9110** [comment]
@kv2019i : Thanks for the suggestion. 
Problem of sound card getting detected with chrome kernel solved by reloading pulse audio modules after reboot. But this needs to be done every time after reboot.

So to check hdmi issue if it exists on linux kernel also, i tried loading sof-hda on linux with default kernel.

I have ubuntu 20.04 with kernel "5.4.0-42-generic". Here sof-hda card only not getting listed. I followed the same steps mentioned above. Got below failed logs wrt to SOF

[    5.070515] sof-audio-pci 0000:00:1f.3: enabling device (0000 -> 0002)
[    5.070748] sof-audio-pci 0000:00:1f.3: warning: No matching ASoC machine driver found
[    5.070752] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040380
[    5.070888] sof-audio-pci 0000:00:1f.3: use msi interrupt mode
[   10.579923] audit: type=1400 audit(1618351746.336:34): apparmor="STATUS" operation="profile_load" profile="unconfined" name="snap.snap-store.ubuntu-software" pid=971 comm="apparmor_parser"
[   10.581096] audit: type=1400 audit(1618351746.340:36): apparmor="STATUS" operation="profile_load" profile="unconfined" name="snap.snap-store.ubuntu-software-local-file" pid=972 comm="apparmor_parser"
[   66.604969] sof-audio-pci 0000:00:1f.3: couldn't bind with audio component
[   66.604986] sof-audio-pci 0000:00:1f.3: error: init i915 and HDMI codec failed
[   66.605215] sof-audio-pci 0000:00:1f.3: error: failed to probe DSP -19
[   66.605217] sof-audio-pci 0000:00:1f.3: error: sof_probe_work failed err: -19
                       
could you please help me here?

**Comment by plbossart** [comment]
@padmashree9110 you will need to update your Ubuntu version, SOF can only work with versions 5.5.11+

**Comment by padmashree9110** [comment]
@plbossart @kv2019i  I tried with ubuntu 20.04 with kernel '5.6.0-050600-generic'. i was able to list sound card and also 3.5mm worked fine. But again HDMI audio is not working.

**Comment by plbossart** [comment]
@padmashree9110 how did you test HDMI? The driver exposes 3 PCM devices but only the ones that are actually connected will generate sound.

Please clarify your test (alsa hw device or PulseAudio?) and share dmesg/alsa-info results.

**Comment by padmashree9110** [comment]
@plbossart 
I was verifying with UI only. I connected HDMI and selected "sof -hda-dsp Stereo" in settings-> sound->output device. So audio was not heard in HDMI, it was falling back to 3.5mm, though 3.5mm is not connected to the device.

I tried with alsa command, out of 3 PCM devices in pc3p hdmi audio is coming properly. Verified with the command
$aplay -D plughw:0,3 Sine_440_10min.wav

But with Ui when i play no sound in hdmi. Some topology related erros were found for hdmi in alsa-info and dmesg. I have shared both the logs :
Attched als-info 
[alsa-info.txt](https://github.com/thesofproject/linux/files/6324239/alsa-info.txt)

Dmesg logs
[dmesg.txt](https://github.com/thesofproject/linux/files/6324245/dmesg.txt)

**Comment by kv2019i** [comment]
Hey @padmashree9110 . Thanks, the attachments are very useful. Basicly they shows i915 driver working as expected, the audio driver makes the connection to i915 driver and that the HDMI/DP codec driver is correctly loaded. So far so good.

But then a problem is that no audio-capable monitor/receiver is listed as being available:
```
		iface CARD
		name 'HDMI/DP,pcm=3 Jack'
		value **false**
...
		iface CARD
		name 'HDMI/DP,pcm=4 Jack'
		value **false**
...
		iface CARD
		name 'HDMI/DP,pcm=5 Jack'
		value **false**
```

So something in detecting the display has gone wrong. Could you attach output of "sudo cat /sys/kernel/debug/dri/0/i915_display_info" on the system?

It should show at least one entry like:
```
[CONNECTOR:95:DP-1]: status: connected
        physical dimensions: 520x320mm
        subpixel order: Unknown
        CEA rev: 3
        DPCD rev: 12
        audio support: **yes**
```

**Comment by padmashree9110** [comment]
@kv2019i Thank you for the confirmation that  driver side everything seems fine. But hdmi monitor is working one only and even it worked fine with alsa command.

CONNECTOR:301:DP-3 shows the above mentioned details properly. I have attached the full logs of /sys/kernel/debug/dri/0/i915_display_info:
[i915_display.txt](https://github.com/thesofproject/linux/files/6325927/i915_display.txt)

**Comment by kv2019i** [comment]
Hmm, this looks like an issue in either i915 driver or the ALSA HDMI codec driver. The i915 log indeed shows an audio capable monitor, so the negotiation towards the monitor has been succesful. The problem is now on the notification send from i915 to audio driver. The ALSA mixer control value is used to driver the GUI logic. E.g. if the notification is lost, the GUI doesn't know there's a HDMI monitor connected, and audio is not routed to it. But your test from console (audio works to PCM3) confirms it's just the monitor notification that is lost.

This could be: https://github.com/thesofproject/linux/issues/1687

This is not fixed in 5.6.x kernels, but it is in 5.7, so this is one thing to try.

With current kernel, could you try to unplug HDMI, replug it, and then observe the monitor status, e.g. with:

$amixer  contents |grep -C2 HDMI/DP
```
numid=14,iface=CARD,name='HDMI/DP,pcm=3 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=20,iface=CARD,name='HDMI/DP,pcm=4 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
numid=26,iface=CARD,name='HDMI/DP,pcm=5 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
```

If the issue is #1687 , then reconnecting should fix it. Also if rootcause is https://github.com/thesofproject/linux/issues/2825 , reconnect should help. This stills a real fix, but this experiments helps to confirm where the issue is.

**Comment by padmashree9110** [comment]
**@kv2019i Reconnecting hdmi didn't fix the issue for me. But  HDMI/DP, pcm3 Jack value is always "true" .  Below are the logs for the same.

$cat alsa-info.txt |grep -C2 HDMI/DP
control.11 {
iface CARD
name 'HDMI/DP,pcm=3 Jack'
value true
comment {

control.17 {
iface CARD
name 'HDMI/DP,pcm=4 Jack'
value false
comment {

control.23 {
iface CARD
name 'HDMI/DP,pcm=5 Jack'
value false
comment {

**Comment by padmashree9110** [comment]
@kv2019i @plbossart Any update on this issue?

**Comment by kv2019i** [comment]
@padmashree9110 wrote:
> **@kv2019i Reconnecting hdmi didn't fix the issue for me. But HDMI/DP, pcm3 Jack value is always "true" . Below are the logs for the same.
> 
> $cat alsa-info.txt |grep -C2 HDMI/DP
> control.11 {
> iface CARD
> name 'HDMI/DP,pcm=3 Jack'
> value true

Now you lost me a bit. In the log you shared earlier, the "HDMI/DP,pcm=3 Jack" definitely was "false" (= sound driver has not detected the monitor and it is not shown in the GUI). But now you state it's "always true". So what changed?

I'd expect if you hit one of the bugs I mentioned, the value would be "false" after system boot, but if you reconnect the HDMI monitor, the state is correctly reflected (i.e. "true" when plugged in). At this point, everything should work, and monitor should be visible in GUI as well.

**Comment by padmashree9110** [comment]
@kv2019i This value is being unstable. Sometimes it shows true and sometimes it is false.

**Comment by padmashree9110** [comment]
yesterday when i checked it showed "false" for 10/10 trails. Today i checked again and  it showed "true" for 9/10 trials and one time it showed false.

**Comment by plbossart** [comment]
maybe a red-herring @padmashree9110, even if your tests include a reboot by the time you can see those mixer values it could be that the audio drivers suspended and somehow the connection information is lost. maybe disabling power management would help see what happens on startup, without any further transitions?

**Comment by kv2019i** [comment]
@padmashree9110 Can you describe how are you testing when you say "showed "false" for 10/10 trails". Is this 10 reboot, 10 reconnects of the monitor?

**Comment by padmashree9110** [comment]
@plbossart I disabled power management things using the command
$sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target
and now also value of HDMI is random only.
Sometimes after reboot it showed value as "true" and sometimes it showed false. 
   Even when the value is "true", hdmi audio is not working with UI. So does this value really has any impact on HDMi playback?

**Comment by padmashree9110** [comment]
@kv2019i Those tests were not with reboot..just with a couple of minutes gap i checked the value.

**Comment by kv2019i** [comment]
@padmashree9110 This is very strange now. The value reflects the state of HDMI connection. On Ubuntu, Pulseaudio will monitor this value and HDMI/DP is only when it is true, the option to route audio to HDMI/DP is shown in audio settings.

I.e. normal sequence is that when you plug in a HDMI monitor, the i915 driver sets up the HDMI display part and if the monitor reports to have audio capability, i915 display driver notifies the SOF ALSA driver that an audio capable monitor is available and the SOF driver will set the HDMI/DP jack control to "true". Pulseaudio will notice this and GNOME Sound Settings will offer option to route audio to the HDMI monitor.

So there are two problems you are seeing:
  - the value of the kcontrol jack connection status is changing at random
  - even if the value is "true", HDMI/DP is not shown in UI

The first one indicate there is some problem with the HDMI connection. It is expected that if the monitor goes to some sleep/standby mode, this is seen as a monitor disconnect. But if the monitor stays up, showing display contents and you are still seeing the value change, then something different is happening.

To debug the first one, I'd need to see DRM logs covering the timeframe when you see the value change value between true and false. You can enable DRM logs with:

```
echo 0x4 > /sys/module/drm/parameters/debug
# test for 15min, you should see amixer contents value change randomly
journalctl -k --since=-15min >kernel-log-with-drm.txt
```

... maybe the HDMI connection is somehow faulty, but then I would expect to see continuous stream of HDMI negotiations in the log with the audio capability coming and going.

**Comment by padmashree9110** [comment]
@kv2019i yes. I am able to see HDMI status change from "connected to disconnected" and also "disconnected to connected" several times in drm logs . I have attached the full logs also.
[kernel-log-with-drm.txt](https://github.com/thesofproject/linux/files/6385471/kernel-log-with-drm.txt)

**Comment by kv2019i** [comment]
@padmashree9110 Ok, that explains. Do you see anything on the display? It's the whole display that is getting disconnected and connected all the time. This can be a problem in the monitor, the cables and/or an issue in i915 driver. Basicly audio is just reacting to the display continuously disappearing and then coming back.

**Comment by padmashree9110** [comment]
Checked monitor and cable on other device, both are working fine only. And also display  on this device is also fine, it is not disconnecting and connecting back again. It is stable.

**Comment by kv2019i** [comment]
@padmashree9110 Thanks. So this starts to seem like a i915 driver issue. I suggest reporting this to https://gitlab.freedesktop.org/drm/intel/-/issues

If possible, I'd also try an even newer kernel, just to see if there is any change. Debugging the pulseaudio configuration issue is pretty impossible if the monitor audio setup is not reliable.

**Comment by kv2019i** [comment]
We did some testing with @padmashree9110 today and:
 - logs show that /sys/kernel/debug/dri/0/i915_display_info shows an audio capable monitor
 - drm:i915_audio_component_get_eld() traces show that towards ALSA, none of the monitors are reported to have audio
 - reloading the driver does not help
 - tested with upstream 5.11 kernel

So this would indeed point to some i915 side issue that we have not seen before.

**Comment by kv2019i** [comment]
Renamed title and assigned for myself for tracking. Discussing with i915 team, will close if we conclude it's an issue on i915 side (and/or add new data here if we get new hints pointing at SOF).

**Comment by keqiaozhang** [comment]
@kv2019i , any updates from i915 side?

**Comment by kv2019i** [comment]
@keqiaozhang It seems the audio monitor detection problem is not seen with upstream i915 version. Waiting for @padmashree9110 to confirm which version worked (with legacy driver). We can evaluate whether this bug should be kept open, or a new opened as there is some problem with SOF driver.

**Comment by padmashree9110** [comment]
@kv2019i  As i mentioned in i915 JIRA it is generic kernel - 5.10.0-051000-generic. Any updates on this?

**Comment by keqiaozhang** [comment]
@padmashree9110 , we are no likely to support this backport fix.

**Comment by padmashree9110** [comment]
We still need support on this. This issue is found with latest kernel (5.11 generic )also as i mentioned. we need not to backport. We can check with the latest kernel only.

**Comment by keqiaozhang** [comment]
@padmashree9110 , please check with the latest kernel version.

**Comment by padmashree9110** [comment]
@keqiaozhang Actually HDA audio is working fine and only SOF-HDA has issues. Worked with @kv2019i and he root caused the issue to be with UCM configuration. Issue is because DMIC is not present on our NUC. So he suggested me to comment out "SectionDevice."Mic1" {" in /usr/share/alsa/ucm2/sof-hda-dsp/HiFi.conf. With this HDMI is getting listed and also working fine but 3.5mm option goes off in GUI.
          Once i comment "SectionDevice."Mic1" {" in /usr/share/alsa/ucm2/sof-hda-dsp/HiFi.conf, 3.5mm detection goes off and it will get listed if i reload modules using $pactl load-module module-detect . Any suggestion here to make both 3.5mm and hdmi visible at once?

**Comment by plbossart** [comment]
Humm, sorry @padmashree9110 @kv2019i , something doesn't add up here.

The SOF driver is only selected when there are digital microphones present on a device. We use the Intel NHLT tables to detect this capability. If there are no DMICs, you don't need to use SOF.
Can you please add this file 
[sof-dyndbg.conf.txt](https://github.com/thesofproject/linux/files/6894638/sof-dyndbg.conf.txt) as /etc/modprobe.d/sof-dyndbg.conf and attach the dmesg log. You should see a number of dmics present.
