### ISSUE TITLE
[FEATURE] Add support for sof-adl-rt711-2ch on HP Omen 16-k0005TX

### ISSUE THREAD

**Issue by AlecJY** [thesofproject/linux#3727]
**Is your feature request related to a problem? Please describe.**
I bought an HP Omen 16-k0005TX recently. The soundcard didn't work on Linux. I try to reload `snd_sof_pci_intel_tgl` then dmesg shows the following messages that sof-adl-rt711-2ch.tplg is not found.

```
[  390.982490] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[  390.982512] sof-audio-pci-intel-tgl 0000:00:1f.3: SoundWire enabled on CannonLake+ platform, using SOF driver
[  390.982704] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[  390.982791] sof-audio-pci-intel-tgl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[  390.989168] sof-audio-pci-intel-tgl 0000:00:1f.3: use msi interrupt mode
[  391.005236] sof-audio-pci-intel-tgl 0000:00:1f.3: DMICs detected in NHLT tables: 2
[  391.005242] sof-audio-pci-intel-tgl 0000:00:1f.3: hda codecs found, mask 4
[  391.005415] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:1:1-3964a
[  391.005417] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:21:0 Kernel ABI 3:19:1
[  391.005419] sof-audio-pci-intel-tgl 0000:00:1f.3: warn: FW ABI is more recent than kernel
[  391.005423] sof-audio-pci-intel-tgl 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
[  391.120009] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:1:1-3964a
[  391.120028] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:21:0 Kernel ABI 3:19:1
[  391.120036] sof-audio-pci-intel-tgl 0000:00:1f.3: warn: FW ABI is more recent than kernel
[  391.125025] soundwire sdw-master-0: Slave Entry not found
[  391.125525] soundwire sdw-master-1: Slave Entry not found
[  391.133608] sof-audio-pci-intel-tgl 0000:00:1f.3: Direct firmware load for intel/sof-tplg/sof-adl-rt711-2ch.tplg failed with error -2
[  391.133618] sof-audio-pci-intel-tgl 0000:00:1f.3: error: tplg request firmware intel/sof-tplg/sof-adl-rt711-2ch.tplg failed err: -2
[  391.133628] sof-audio-pci-intel-tgl 0000:00:1f.3: you may need to download the firmware from https://github.com/thesofproject/sof-bin/
[  391.133631] sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to load DSP topology -2
[  391.133634] sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: error at snd_soc_component_probe on 0000:00:1f.3: -2
[  391.133650] sof_sdw sof_sdw: ASoC: failed to instantiate card -2
[  391.133775] sof_sdw sof_sdw: snd_soc_register_card failed -2
[  391.133779] sof_sdw: probe of sof_sdw failed with error -2
[  393.157068] soundwire sdw:3:025d:1316:01:0: Probe not complete, timed out
[  393.157103] soundwire sdw:3:025d:1316:01:0: Update Slave status failed:-110
[  393.157144] soundwire sdw:0:025d:0711:01:0: Probe not complete, timed out
[  393.157153] soundwire sdw:0:025d:0711:01:0: Update Slave status failed:-110
```

I also tried with renaming `sof-adl-rt711.tplg` and `sof-adl-rt711-4ch.tplg` to `sof-adl-rt711-2ch.tplg`, but it still didn't work. The following is the dmesg log.
```
[ 1811.139617] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[ 1811.139652] sof-audio-pci-intel-tgl 0000:00:1f.3: SoundWire enabled on CannonLake+ platform, using SOF driver
[ 1811.139984] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[ 1811.140102] sof-audio-pci-intel-tgl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[ 1811.146769] sof-audio-pci-intel-tgl 0000:00:1f.3: use msi interrupt mode
[ 1811.162141] sof-audio-pci-intel-tgl 0000:00:1f.3: DMICs detected in NHLT tables: 2
[ 1811.162145] sof-audio-pci-intel-tgl 0000:00:1f.3: hda codecs found, mask 4
[ 1811.162336] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:1:1-3964a
[ 1811.162338] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:21:0 Kernel ABI 3:19:1
[ 1811.162340] sof-audio-pci-intel-tgl 0000:00:1f.3: warn: FW ABI is more recent than kernel
[ 1811.162343] sof-audio-pci-intel-tgl 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
[ 1811.276182] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:1:1-3964a
[ 1811.276202] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:21:0 Kernel ABI 3:19:1
[ 1811.276210] sof-audio-pci-intel-tgl 0000:00:1f.3: warn: FW ABI is more recent than kernel
[ 1811.281201] soundwire sdw-master-1: Slave Entry not found
[ 1811.281413] sof-audio-pci-intel-tgl 0000:00:1f.3: Topology: ABI 3:21:0 Kernel ABI 3:19:1
[ 1811.281424] sof-audio-pci-intel-tgl 0000:00:1f.3: warn: topology ABI is more recent than kernel
[ 1811.281527] sof-audio-pci-intel-tgl 0000:00:1f.3: error: can't connect DAI HDA3.OUT stream iDisp4
[ 1811.281536] sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to add widget id 0 type 27 name : HDA3.OUT stream iDisp4
[ 1811.281543] sof_sdw sof_sdw: ASoC: failed to load widget HDA3.OUT
[ 1811.281546] sof_sdw sof_sdw: ASoC: topology: could not load header: -22
[ 1811.281565] sof-audio-pci-intel-tgl 0000:00:1f.3: error: tplg component load failed -22
[ 1811.281578] sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to load DSP topology -22
[ 1811.281581] sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: error at snd_soc_component_probe on 0000:00:1f.3: -22
[ 1811.281609] sof_sdw sof_sdw: ASoC: failed to instantiate card -22
[ 1811.281955] sof_sdw sof_sdw: snd_soc_register_card failed -22
[ 1811.281958] sof_sdw: probe of sof_sdw failed with error -22
[ 1811.301675] soundwire sdw-master-0: Slave Entry not found
```

**Describe the solution you'd like**
It would be appreciated if add support for `sof-adl-rt711-2ch`.

**Additional context**
[alsa-info log](http://alsa-project.org/db/?f=c579667889c64649506c9b263cb895262e0fbf4a)

**Comment by plbossart** [comment]
@AlecJY unfortunately it's likely that we will need topology and machine driver changes to support this HP platform. It's not the first time this happens, it was the same mess with TigerLake. 

Can you please add this file
[sof-dyndbg.conf.txt](https://github.com/thesofproject/sof/files/9001428/sof-dyndbg.conf.txt)
 as /etc/modprobe.d/sof-dyndbg.conf (the extension does matter), reboot and attach the entire dmesg log.

If you can also add the result of 

````
ls /sys/bus/soundwire/devices/
````
and

````
cat /sys/bus/acpi/devices/*/adr  | grep 025d
````

**Comment by AlecJY** [comment]
[dmesg.log](https://github.com/thesofproject/sof/files/9002240/dmesg.log)

And the result of the two commands

```bash
$ ls /sys/bus/soundwire/devices/
sdw:0:025d:0711:00  sdw:0:025d:0711:01:0  sdw:3:025d:1316:01:0  sdw-master-0  sdw-master-1
```

```bash
$ cat /sys/bus/acpi/devices/*/adr  | grep 025d
0x000020025d071100
0x000120025d071100
```

**Comment by plbossart** [comment]
Thanks @AlecJY 

ok, so the BIOS/DSDT is completely wrong. HP declared the SAME rt711 (headset) on two links, but in reality it's really a rt711-sdca (new version!) on link0 and rt1316 on link1. What a complete fail.

I'll prepare a set of patches but you'll have to compile your own kernel

**Comment by plbossart** [comment]
@AlecJY Please try the last three patches in https://github.com/thesofproject/linux/pull/3725

You will need do this as well, we'll release an update later on for topologies.

````
cd /lib/firmware/intel/sof-tplg

cp sof-tgl-rt711-rt1308-2ch.tplg sof-adl-rt711-l0-rt1326-l1-2ch.tplg
````

**Comment by plbossart** [comment]
@AlecJY if you don't know how to build the kernel, see https://thesofproject.github.io/latest/getting_started/setup_linux/prepare_build_environment.html and 
https://thesofproject.github.io/latest/getting_started/setup_linux/install_locally.html

**Comment by AlecJY** [comment]
The soundcard still did not work, and there's nothing under `/sys/bus/soundwire/devices/`.

[dmesg.log](https://github.com/thesofproject/linux/files/9011239/dmesg.log)
[alsa-info log](http://alsa-project.org/db/?f=489247b8c2586530d4caff00042cdd9d584da3d3)

**Comment by plbossart** [comment]
@AlecJY you seem to have a kernel configuration issue. Make sure that SOF is enabled. You can also use 'blacklist snd-hda-intel' to see what happens.

Here are a set of configs you'll need:

````
CONFIG_SND_SOC_INTEL_SOUNDWIRE_SOF_MACH=m
CONFIG_SND_SOC_SOF_TOPLEVEL=y
CONFIG_SND_SOC_SOF_PCI_DEV=m
CONFIG_SND_SOC_SOF_PCI=m
CONFIG_SND_SOC_SOF_ALDERLAKE=m
CONFIG_SND_SOC_SOF_HDA_COMMON=m
CONFIG_SND_SOC_SOF_HDA_LINK=y
CONFIG_SND_SOC_SOF_HDA_AUDIO_CODEC=y
CONFIG_SND_SOC_SOF_HDA_LINK_BASELINE=m
CONFIG_SND_SOC_SOF_HDA=m
CONFIG_SND_SOC_SOF_HDA_PROBES=m
CONFIG_SND_SOC_SOF_INTEL_SOUNDWIRE_LINK_BASELINE=m
CONFIG_SND_SOC_SOF_INTEL_SOUNDWIRE=m
CONFIG_REGMAP_SOUNDWIRE=m
CONFIG_REGMAP_SOUNDWIRE_MBQ=m
CONFIG_SND_INTEL_SOUNDWIRE_ACPI=m
CONFIG_SND_SOC_INTEL_SOUNDWIRE_SOF_MACH=m
CONFIG_SND_SOC_SOF_INTEL_SOUNDWIRE_LINK_BASELINE=m
CONFIG_SND_SOC_SOF_INTEL_SOUNDWIRE=m
CONFIG_SOUNDWIRE=m
CONFIG_SOUNDWIRE_CADENCE=m
CONFIG_SOUNDWIRE_INTEL=m
# CONFIG_SOUNDWIRE_QCOM is not set
CONFIG_SOUNDWIRE_GENERIC_ALLOCATION=m
````

**Comment by AlecJY** [comment]
I found that `CONFIG_SND_SOC_SOF_ALDERLAKE` was not set, thank you. However, the sound card still didn't work.

There is something changed in `/sys/bus/soundwire/devices/`
```
$ ls /sys/bus/soundwire/devices/
sdw:0:025d:0711:01  sdw:3:025d:1316:01:0  sdw-master-0  sdw-master-1
```
[dmesg.log](https://github.com/thesofproject/linux/files/9012306/dmesg.log)

**Comment by plbossart** [comment]
ok, so the remapping seems to work but the wrong topology is still chosen

````
[    5.748855] acpi PRP00001:00: Creating 4 SDW Link devices
[    5.749046] soundwire sdw-master-0: remapped _ADR 0x20025d071100 as 0x30025d071101
[    5.749047] soundwire sdw-master-0: SDW Slave Addr: 30025d071101
[    5.749048] soundwire sdw-master-0: SDW Slave class_id 0x01, mfg_id 0x025d, part_id 0x0711, unique_id 0x0, version 0x3
[    5.749054] soundwire sdw-master-0: remapped _ADR 0x120025d071100 as 0x130025d131601
[    5.749123] soundwire sdw-master-0: remapped _ADR 0x120025d071100 as 0x130025d131601
[    5.749268] soundwire sdw-master-1: remapped _ADR 0x20025d071100 as 0x30025d071101
[    5.749272] soundwire sdw-master-1: remapped _ADR 0x120025d071100 as 0x130025d131601

[    5.757051] sof-audio-pci-intel-tgl 0000:00:1f.3: SoundWire machine driver sof_sdw topology sof-adl-rt711-2ch.tplg
````

**Comment by plbossart** [comment]
No that's wrong:
````
sdw:0:025d:0711:01  sdw:3:025d:1316:01:0
````

I may have things mixed-up in the 64-bit values.

**Comment by plbossart** [comment]
should be 
````
sdw:0:025d:0711:01  sdw:1:025d:1316:01
````

**Comment by plbossart** [comment]
It seems there's a disconnect in some of the earlier reports @AlecJY 

Can you revert to plain vanilla v5.19-rc2 kernel, without any of my 3 patches, and provide the dmesg log and two commands

$ ls /sys/bus/soundwire/devices/
$ cat /sys/bus/acpi/devices/*/adr  | grep 025d

**Comment by plbossart** [comment]
And better yet, extract the DSDT from this device

apt install acpica-tools
cat /sys/firmware/acpi/tables/DSDT > dsdt.dat
iasl -d dsdt.dat
cp dsdt.dsl dsdt.dsl.txt 

and attach dsdt.dsl.txt

Thanks!

**Comment by AlecJY** [comment]
```bash
$ ls /sys/bus/soundwire/devices/
sdw:0:025d:0711:00  sdw:0:025d:0711:01:0  sdw:3:025d:1316:01:0  sdw-master-0  sdw-master-1
```

```bash
$ cat /sys/bus/acpi/devices/*/adr | grep 025d
0x000020025d071100
0x000120025d071100
```

[dmesg.log](https://github.com/thesofproject/linux/files/9013074/dmesg.log)
[dsdt.dsl.txt](https://github.com/thesofproject/linux/files/9013077/dsdt.dsl.txt)

**Comment by plbossart** [comment]
thanks @AlecJY 

wow, that's weird. there isn't an entry in the DSDT table for the 1316 device, so no idea how it shows up in the device list.

**Comment by plbossart** [comment]
@AlecJY I have a hunch that the coexistence between RT711 (v2) and RT711-sdca (v3) creates all kinds of problems with device names that conflicts. Can you retest v5.19-rc2 with this patch on top?

https://github.com/thesofproject/linux/commit/33978383df6caa0ba076701598571d17b6d62272.patch

**Comment by AlecJY** [comment]
```
$ ls /sys/bus/soundwire/devices/
sdw:0:025d:0711:2:00  sdw:0:025d:0711:3:01:0  sdw:3:025d:1316:3:01:0  sdw-master-0  sdw-master-1
```

```
cat /sys/bus/acpi/devices/*/adr | grep 025d
0x000020025d071100
0x000120025d071100
```
[dmesg.log](https://github.com/thesofproject/linux/files/9019961/dmesg.log)

**Comment by plbossart** [comment]
Thanks @AlecJY 

I will need to spend more time on this, this configuration seems to create a lot of problems. I can't figure out why the first device sdw:0:025d:0711:2:00 is missing the extension (unique ID) and why we are missing the second device 0x000120025d071100

**Comment by plbossart** [comment]
@AlecJY Let's first try to revert one change to only focus on the ACPI devices. Can you try the updated patches in PR #3730 https://github.com/thesofproject/linux/pull/3730

Thanks! I realize it's painful but I don't have the hardware to test myself.

**Comment by AlecJY** [comment]
```bash
$ ls /sys/bus/soundwire/devices/
sdw:0:025d:0711:2:00  sdw-master-0  sdw-master-1
```

```bash
$ cat /sys/bus/acpi/devices/*/adr | grep 025d
0x000020025d071100
0x000120025d071100
```

[dmesg.log](https://github.com/thesofproject/linux/files/9020756/dmesg.log)

**Comment by plbossart** [comment]
wow, so there's really something wrong in the logic to create device from the ACPI description. Thanks @AlecJY 

I added more dev_dbg traces to figure out what happens, please try the update in PR #3730 

We must have missed something in the past on how devices are handled.

**Comment by AlecJY** [comment]
```bash
$ ls /sys/bus/soundwire/devices/
sdw:0:025d:0711:2:00  sdw-master-0  sdw-master-1
```

```bash
$ cat /sys/bus/acpi/devices/*/adr | grep 025d
0x000020025d071100
0x000120025d071100
```
[dmesg.log](https://github.com/thesofproject/linux/files/9021730/dmesg.log)

**Comment by plbossart** [comment]
Fascinating @AlecJY. Somehow we are using link3 but the second device is advertised on Link1...

````
[    5.603258] acpi PRP00001:00: Creating 4 SDW Link devices

[    5.603412] soundwire sdw-master-0: sdw_acpi_find_slaves: trying to find devices for link id 0
[    5.603417] soundwire sdw-master-0: SDW Slave Addr: 20025d071100
[    5.603418] soundwire sdw-master-0: SDW Slave class_id 0x00, mfg_id 0x025d, part_id 0x0711, unique_id 0x0, version 0x2
[    5.603419] soundwire sdw-master-0: sdw_acpi_find_slaves: skipping same device
[    5.603423] soundwire sdw-master-0: Link id 1 does not match bus link id 0, ignoring ADR 0x120025d071100
[    5.603424] soundwire sdw-master-0: sdw_acpi_find_slaves: skipping irrelevant/invalid device
[    5.603467] soundwire sdw-master-0: Link id 1 does not match bus link id 0, ignoring ADR 0x120025d071100
[    5.603467] soundwire sdw-master-0: sdw_acpi_find_slaves: No valid child device found, continuing
[    5.603468] soundwire sdw-master-0: sdw_acpi_find_slaves: done trying to find devices for link id 0

[    5.603564] soundwire sdw-master-1: sdw_acpi_find_slaves: trying to find devices for link id 3
[    5.603567] soundwire sdw-master-1: Link id 0 does not match bus link id 3, ignoring ADR 0x20025d071100
[    5.603567] soundwire sdw-master-1: sdw_acpi_find_slaves: No valid child device found, continuing
[    5.603570] soundwire sdw-master-1: Link id 1 does not match bus link id 3, ignoring ADR 0x120025d071100
[    5.603570] soundwire sdw-master-1: sdw_acpi_find_slaves: No valid child device found, continuing
[    5.603570] soundwire sdw-master-1: sdw_acpi_find_slaves: done trying to find devices for link id 3
````

so now the question is why on earth this link3 is used. I'll add some more patches for the Intel part.

**Comment by plbossart** [comment]
@AlecJY can you please add this to /etc/modprobe.d/sof-dyndbg.conf, reboot and provide the dmesg log again?

````
options snd_intel_sdw_acpi dyndbg=+pmf
````

**Comment by AlecJY** [comment]
[dmesg.log](https://github.com/thesofproject/linux/files/9021907/dmesg.log)

**Comment by plbossart** [comment]
ok, I think I have things mostly figured out now @AlecJY 
It turns out the ACPI entry for the second device uses a link that's disabled, so the remap didn't work. Using link3 should work now, please try the updated PR #3730 and copy/unzip this topology file 
[sof-adl-rt711-l0-rt1316-l3-2ch.tplg.gz](https://github.com/thesofproject/linux/files/9022381/sof-adl-rt711-l0-rt1316-l3-2ch.tplg.gz)
as /lib/firmware/intel/sof-tplg/sof-adl-rt711-l0-rt1316-l3-2ch.tplg

That should go a bit further.

**Comment by plbossart** [comment]
Sorry @AlecJY, my initial patch to add the version number creates other issues.

I updated the PR #3730 (commit b8c67c25d44e8c586d99a7bbb43539ba7f4c171b) which *should* work now...

**Comment by AlecJY** [comment]
The sound card still didn't work unfortunately.

```bash
$ ls /sys/bus/soundwire/devices/
sdw:0:025d:0711:01  sdw:3:025d:1316:01  sdw-master-0  sdw-master-1
```

```bash
$ cat /sys/bus/acpi/devices/*/adr | grep 025d
0x000020025d071100
0x000120025d071100
```

[dmesg.log](https://github.com/thesofproject/linux/files/9024844/dmesg.log)

**Comment by plbossart** [comment]
Thanks @AlecJY. The SoundWire part is now working as expected, the headset codec and amplifier are discovered, enumerated and initialized. That's progress :-)

````
    5.764402] soundwire_intel soundwire_intel.link.0: Slave status change: 0x2
[    5.764406] soundwire sdw-master-0: Slave attached, programming device number
[    5.764458] soundwire_intel soundwire_intel.link.3: Slave status change: 0x2
[    5.764461] soundwire sdw-master-1: Slave attached, programming device number
[    5.764651] soundwire sdw-master-1: SDW Slave Addr: 30025d131601
[    5.764652] soundwire sdw-master-1: SDW Slave class_id 0x01, mfg_id 0x025d, part_id 0x1316, unique_id 0x0, version 0x3
[    5.764734] soundwire sdw-master-0: SDW Slave Addr: 30025d071101
[    5.764735] soundwire sdw-master-0: SDW Slave class_id 0x01, mfg_id 0x025d, part_id 0x0711, unique_id 0x0, version 0x3
[    5.764982] soundwire_intel soundwire_intel.link.3: Msg ignored for Slave 0
[    5.764983] soundwire sdw-master-1: No more devices to enumerate
[    5.764995] soundwire_intel soundwire_intel.link.0: Msg ignored for Slave 0
[    5.764996] soundwire sdw-master-0: No more devices to enumerate
[    5.765018] soundwire_intel soundwire_intel.link.0: Slave status change: 0x200001
[    5.765021] rt711-sdca sdw:0:025d:0711:01: signaling enumeration completion for Slave 5
[    5.765042] soundwire_intel soundwire_intel.link.3: Slave status change: 0x20001
[    5.765045] rt1316-sdca sdw:3:025d:1316:01: signaling enumeration completion for Slave 4
[    5.765228] rt1316-sdca sdw:3:025d:1316:01: Configured bus base 1, scale 3, mclk 19200000, curr_freq 4800000
[    5.765232] rt711-sdca sdw:0:025d:0711:01: Configured bus base 1, scale 3, mclk 19200000, curr_freq 4800000
````

What doesn't work is the detection of the machine driver. 

````
[    5.771178] sof-audio-pci-intel-tgl 0000:00:1f.3: loading topology:intel/sof-tplg/sof-adl-rt711-2ch.tplg
[    5.771360] sof-audio-pci-intel-tgl 0000:00:1f.3: Direct firmware load for intel/sof-tplg/sof-adl-rt711-2ch.tplg failed with error -2
[    5.771364] sof-audio-pci-intel-tgl 0000:00:1f.3: error: tplg request firmware intel/sof-tplg/sof-adl-rt711-2ch.tplg failed err: -2
[    5.771364] sof-audio-pci-intel-tgl 0000:00:1f.3: you may need to download the firmware from https://github.com/thesofproject/sof-bin/
[    5.771365] sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to load DSP topology -2
[    5.771366] sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: error at snd_soc_component_probe on 0000:00:1f.3: -2
[    5.771383] sof_sdw sof_sdw: ASoC: failed to instantiate card -2
[    5.771664] sof_sdw sof_sdw: snd_soc_register_card failed -2
````

Looking into it.

**Comment by plbossart** [comment]
Typo on my side:
````
		.link_mask = 0xB, /* 2 active links required */ <<< broken, that would expect link0, 1 and 3 enabled.
		.links = adl_sdw_rt711_link0_rt1316_link3,
````

Should be 		
```
.link_mask = 0x9, /* 2 active links required */ << link0 and link3 enabled
````

PR #3730 updated, thanks @AlecJY for your patience and help on this one.

**Comment by AlecJY** [comment]
```bash
$ ls /sys/bus/soundwire/devices/
sdw:0:025d:0711:01  sdw:3:025d:1316:01  sdw-master-0  sdw-master-1
```

```bash
$ cat /sys/bus/acpi/devices/*/adr | grep 025d
0x000020025d071100
0x000120025d071100
```

[dmesg.log](https://github.com/thesofproject/linux/files/9029390/dmesg.log)

**Comment by plbossart** [comment]
D'oh, no idea what's going on @AlecJY. 

Please try with the updated branch, I added more traces to see why we skip the machine driver entry and use the sof-adl-rt711 version. Thanks!

**Comment by AlecJY** [comment]
```bash
$ ls /sys/bus/soundwire/devices/
sdw:0:025d:0711:01  sdw:3:025d:1316:01  sdw-master-0  sdw-master-1
```

```bash
$ cat /sys/bus/acpi/devices/*/adr | grep 025d
0x000020025d071100
0x000120025d071100
```

[dmesg.log](https://github.com/thesofproject/linux/files/9030062/dmesg.log)

**Comment by plbossart** [comment]
ok, I had more mistake in the ACPI table with a missing empty entry {}

Also added more traces in case I screwed up even more. Update pushed, please give it a try @AlecJY

**Comment by AlecJY** [comment]
```bash
$ ls /sys/bus/soundwire/devices/
sdw:0:025d:0711:01  sdw:3:025d:1316:01  sdw-master-0  sdw-master-1
```

```bash
$ cat /sys/bus/acpi/devices/*/adr | grep 025d
0x000020025d071100
0x000120025d071100
```

[dmesg.log](https://github.com/thesofproject/linux/files/9030396/dmesg.log)

**Comment by plbossart** [comment]
ok, now we seem to have lost the 2ch DMIC detection. Darn.

````
Direct firmware load for intel/sof-tplg/sof-adl-rt711-l0-rt1316-l3.tplg failed with error -2
````

**Comment by plbossart** [comment]
Again this HP platform breaks existing assumptions that link2 and link3 are used by DMIC.
This should help
````diff
-                       if (!(mach->link_mask & GENMASK(3, 2))) {
+                       if (hweight_long(mach->link_mask) <= 2) {
````

PR #3730 updated @AlecJY. I just need the dmesg log now, the device handling is fine.

**Comment by plbossart** [comment]
@bardliao @RanderWang FYI, wondering if the change above will break existing platforms or require topologies we haven't released?

**Comment by AlecJY** [comment]
[dmesg.log](https://github.com/thesofproject/linux/files/9032316/dmesg.log)

**Comment by bardliao** [comment]
> @bardliao @RanderWang FYI, wondering if the change above will break existing platforms or require topologies we haven't released?

@plbossart It will break the existing platforms ONLY if the platform uses less then 2 SoundWire links AND doesn't use DMIC, right? In addition to checking link mask, we check dmic number from nhlt. So I think it is safe for this change.

**Comment by plbossart** [comment]
> [dmesg.log](https://github.com/thesofproject/linux/files/9032316/dmesg.log)

ok thanks @AlecJY this is now a topology issue, I'll have to look into this later today.

**Comment by plbossart** [comment]
> > @bardliao @RanderWang FYI, wondering if the change above will break existing platforms or require topologies we haven't released?
> 
> @plbossart It will break the existing platforms ONLY if the platform uses less then 2 SoundWire links AND doesn't use DMIC, right? In addition to checking link mask, we check dmic number from nhlt. So I think it is safe for this change.

Not following @bardliao, are you saying the changes are ok or something else needs to be added?

**Comment by plbossart** [comment]
the logs show this
````
[    5.781436] sof_sdw sof_sdw: create dai link SDW3-Playback, id 2
[    5.781437] sof_sdw sof_sdw: create dai link SDW3-Capture, id 3
````

That makes sense, the 'SDW3' means that we are using the link3 for speaker playback. The problem is that the topology hard-codec SDW1, will change that.

**Comment by plbossart** [comment]
@AlecJY please try again with this topology file.

[sof-adl-rt711-l0-rt1316-l3-2ch.tplg.gz](https://github.com/thesofproject/linux/files/9048126/sof-adl-rt711-l0-rt1316-l3-2ch.tplg.gz)


````diff
diff --git a/tools/topology/topology1/sof-tgl-rt711-rt1308.m4 b/tools/topology/topology1/sof-tgl-rt711-rt1308.m4
index d9469162b..ea7343c8f 100644
--- a/tools/topology/topology1/sof-tgl-rt711-rt1308.m4
+++ b/tools/topology/topology1/sof-tgl-rt711-rt1308.m4
@@ -224,7 +224,7 @@ ifdef(`EXT_AMP',
 # playback DAI is ALH(SDW1 PIN2) using 2 periods
 # Buffers use s24le format, with 48 frame per 1000us on core 0 with priority 0
 DAI_ADD(sof/pipe-dai-playback.m4,
-       3, ALH,  eval(AMP_1_LINK * 256 + 2), SDW1-Playback,
+       3, ALH,  eval(AMP_1_LINK * 256 + 2), `SDW'eval(AMP_1_LINK)`-Playback',
        PIPELINE_SOURCE_3, 2, s24le,
        1000, 0, 0, SCHEDULE_TIME_DOMAIN_TIMER)
 ')
@@ -290,7 +290,7 @@ DAI_CONFIG(ALH, 3, 1, SDW0-Capture,
 ifdef(`EXT_AMP',
 `
 #ALH SDW1 Pin2 (ID: 2)
-DAI_CONFIG(ALH, eval(AMP_1_LINK * 256 + 2), 2, SDW1-Playback,
+DAI_CONFIG(ALH, eval(AMP_1_LINK * 256 + 2), 2, `SDW'eval(AMP_1_LINK)`-Playback',
        ALH_CONFIG(ALH_CONFIG_DATA(ALH, eval(AMP_1_LINK * 256 + 2), 48000, 2)))
 ')
````

**Comment by AlecJY** [comment]
[dmesg.log](https://github.com/thesofproject/linux/files/9048222/dmesg.log)

**Comment by plbossart** [comment]
Nice, so now we have a hard-coded assumption in the topology again

````
ifelse(PLATFORM, `adl', `
# PCM14 <---> passthrough <---> SSP2 BT playback/capture
', `')
````

That's clearly wrong and needs to be a parameter. Will fix. Thanks for your patience @AlecJY, this platform is exposing all kinds of issues.

**Comment by plbossart** [comment]
@AlecJY please try this file 
[sof-adl-rt711-l0-rt1316-l3-2ch.tplg.gz](https://github.com/thesofproject/linux/files/9048323/sof-adl-rt711-l0-rt1316-l3-2ch.tplg.gz)

**Comment by AlecJY** [comment]
[dmesg.log](https://github.com/thesofproject/linux/files/9048349/dmesg.log)

**Comment by plbossart** [comment]
Ah yes, echo reference is exposed for rt1316 so there's an off-by-one. Try this updated file @AlecJY 

[sof-adl-rt711-l0-rt1316-l3-2ch.tplg.gz](https://github.com/thesofproject/linux/files/9048532/sof-adl-rt711-l0-rt1316-l3-2ch.tplg.gz)

**Comment by bardliao** [comment]
> > > @bardliao @RanderWang FYI, wondering if the change above will break existing platforms or require topologies we haven't released?
> > 
> > 
> > @plbossart It will break the existing platforms ONLY if the platform uses less then 2 SoundWire links AND doesn't use DMIC, right? In addition to checking link mask, we check dmic number from nhlt. So I think it is safe for this change.
> 
> Not following @bardliao, are you saying the changes are ok or something else needs to be added?

@plbossart Yes, the change looks good to me.

**Comment by AlecJY** [comment]
The sound card works!!! It seems that the speakers, microphones and headset jack work normally. Thank you.

There is only one thing I'm not sure if it is a bug. When I tried to record sound with the headset microphone using Audacity, only the right channel received the sound. However, both channels worked on Windows.

[dmesg.log](https://github.com/thesofproject/linux/files/9053490/dmesg.log)
[alsa-info log](http://alsa-project.org/db/?f=dc5e2c8e53a557d2084be407813121f468cc71e9)

**Comment by plbossart** [comment]
Great, thanks @AlecJY for the reports.

Can you try to change this code to see if this changes the headset detection? 

````diff
diff --git a/sound/soc/intel/boards/sof_sdw.c b/sound/soc/intel/boards/sof_sdw.c
index eede9b55e06f..f50f20e958d2 100644
--- a/sound/soc/intel/boards/sof_sdw.c
+++ b/sound/soc/intel/boards/sof_sdw.c
@@ -332,7 +332,7 @@ static const struct dmi_system_id sof_sdw_quirk_table[] = {
                        DMI_MATCH(DMI_PRODUCT_NAME, "OMEN by HP Gaming Laptop 16-k0xxx"),
                },
                .driver_data = (void *)(SOF_SDW_TGL_HDMI |
-                                       RT711_JD2),
+                                       RT711_JD1),
        },
        /* MeteorLake devices */
        {
````

**Comment by AlecJY** [comment]
Still have the same problem.

[dmesg.log](https://github.com/thesofproject/linux/files/9055834/dmesg.log)

**Comment by plbossart** [comment]
@shumingfan can you help with the jack settings? It's surprising that JD1 or JD2 doesn't seem to have an effect, and I am not sure what could happen with the left channel silent. I am not sure what could possibly happen, headset mics are typically mono, maybe an OMTP/CTIA issue?

**Comment by shumingfan** [comment]
@AlecJY Could you dump registers while recording?
cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01/registers
cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01-sdw-mbq/registers

Another test I want to try is the loopback that makes ADC data to DAC.
The loopback setting shows below.
```
@@ -1565,6 +1756,10 @@ int rt711_sdca_io_init(struct device *dev, struct sdw_slave *slave)
        regmap_write(rt711->regmap,
                SDW_SDCA_CTL(FUNC_NUM_JACK_CODEC, RT711_SDCA_ENT_OT1, RT711_SDCA_CTL_VENDOR_DEF, 0), 0x4);

+       // ADC->DAC loopback test
+       rt711_sdca_index_update_bits(rt711, RT711_VENDOR_REG,
+               0x07, 0x0800, 0x0800);
+
        /*
         * if set_jack callback occurred early than io_init,
```
You could playback silent data and enable the recording. Could you hear the sound from the headset mic to the headset headphones?
Please test JD1/JD2 separately. I am not sure which JD source your platform uses.

**Comment by RanderWang** [comment]
> @bardliao @RanderWang FYI, wondering if the change above will break existing platforms or require topologies we haven't released?

I can't image a case would be broken, it is good for me.

**Comment by AlecJY** [comment]
JD1:
Ouput of `cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01/registers`
[JD1-output1.log](https://github.com/thesofproject/linux/files/9060890/JD1-output1.log)

Output of  `cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01-sdw-mbq/registers`
[JD1-output2.log](https://github.com/thesofproject/linux/files/9060895/JD1-output2.log)

JD2:
Ouput of `cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01/registers`
[JD2-output1.log](https://github.com/thesofproject/linux/files/9060901/JD2-output1.log)

Output of  `cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01-sdw-mbq/registers`
[JD2-output2.log](https://github.com/thesofproject/linux/files/9060903/JD2-output2.log)


> You could playback silent data and enable the recording. Could you hear the sound from the headset mic to the headset headphones?

I can't hear any sound from headset mic with both JD1 and JD2.

**Comment by shumingfan** [comment]
@AlecJY  It is weird that the driver can detect CTIA jack type whether using JD1 or JD2.
I will check this with the internal HW engineer. Will give back soon.

**Comment by shumingfan** [comment]
@AlecJY
I got the same machine and reproduce this issue on my side.
I found the root cause that the 'PGA2.0 2 Master Capture Volume' sets the 0 to the left channel.
Please input the command to set the volume.
`amixer -c<card number> cset name='PGA2.0 2 Master Capture Volume' 50,50`

BTW, the JD source should select JD2.

**Comment by AlecJY** [comment]
The problem is solved after running the command. Thank you!

**Comment by plbossart** [comment]
@shumingfan @bardliao I don't see this mixer value being set in UCM, and it's an SOF mixer value that should be set to 0dB on both channels. We need to fix this without asking people to play with amixer, otherwise other folks will have the same issue.

Besides, we don't have any references to the PGA stuff any longer, see https://github.com/alsa-project/alsa-ucm-conf/commit/b856040ab9f3eb0380014959f91ca13afe33a067

**Comment by bardliao** [comment]
@plbossart We should set to 0dB for all platforms. Probable add a new file for SOF mixers in https://github.com/alsa-project/alsa-ucm-conf/tree/master/ucm2/Intel/SOF? @libinyang What do you think?

**Comment by plbossart** [comment]
@ranj063 aren't those controls initialized by default to 0dB? Not sure why we would need an UCM file to alter the default that the topology should do already. Thanks!

**Comment by plbossart** [comment]
@AlecJY I am told there's a tentative fix available made available by the Quanta BIOS team at https://drive.google.com/file/d/1ZjX-Gvb_Zy948t2f44D4gXIiiXVZbdfp/view. 

If you are willing to give this update a try that would be appreciated. You may want to make sure you have a BIOS backup or something to go back to the previious solution should any problems occur.

**Comment by AlecJY** [comment]
@plbossart I tried to update the BIOS with the utility. However, it showed this.

![image](https://user-images.githubusercontent.com/9132996/190451333-6ea2af84-3676-4afe-9ca3-49fc2b18e7f8.png)

I also tried to install with recovery USB, but it showed another error message.

![image](https://user-images.githubusercontent.com/9132996/190452870-7bce4fba-d6bb-4138-9092-dd25a1e8fa0e.png)

**Comment by plbossart** [comment]
Thanks @AlecJY. Quanta confirmed that end-users cannot install non 'formal' BIOS releases so they will have to do the validation. Sorry for the noise and thanks for your tests.

**Comment by shourove000** [comment]
![354053927_292069906500188_4598077252978343396_n](https://github.com/thesofproject/linux/assets/49043946/f18a33f1-6c5a-49b1-a706-e2f4932703ce)
Equalizer is not available in headphone after reinstalling windows,, i updated the audio driver but still facing this problem,,, anyone please help.

**Comment by plbossart** [comment]
> ![354053927_292069906500188_4598077252978343396_n](https://user-images.githubusercontent.com/49043946/246321544-f18a33f1-6c5a-49b1-a706-e2f4932703ce.jpg) Equalizer is not available in headphone after reinstalling windows,, i updated the audio driver but still facing this problem,,, anyone please help.

not an SOF bug, please see through HP/Windows support channels.
